services:
  ec2-app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: ec2-app
    ports:
      - "8082:80"
      - "8000:8000"
    tty: true
    stdin_open: true 

    command: >
      bash -c 'php-fpm &
      php artisan serve --host 0.0.0.0 &
      nginx -g "daemon off;"
      '

    volumes:
      - ./src:/var/www/html
      - ./docker/app/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/html/index.html:/usr/share/nginx/html/index.html