services:
  ec2-app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: ec2-app
    ports:
      - "8082:80"
      - "8000:8000"
    tty: true
    stdin_open: true

    command: >
      bash -c 'php-fpm &
      php artisan serve --host 0.0.0.0 &
      nginx -g "daemon off;"
      '

    volumes:
      - ./src:/var/www/html
      - ./docker/app/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/html/index.html:/usr/share/nginx/html/index.html

  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_test
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password

volumes:
  mysql-volume:
